// ignore_for_file: always_specify_types
// ignore_for_file: camel_case_types
// ignore_for_file: non_constant_identifier_names

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint
import 'dart:ffi' as ffi;
import 'package:ffi/ffi.dart' as pkg_ffi;

/// C bindings for ditto.h
///
/// Regenerate bindings with `dart run ffigen --config ffigen.yaml`.
///
class DittoBindings {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  DittoBindings(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  DittoBindings.fromLookup(
      ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
          lookup)
      : _lookup = lookup;

  /// Returns 0 on success, non-zero on error.
  /// On success, *out_db is a valid handle. Call ditto_close() when done.
  int ditto_open(
    ffi.Pointer<pkg_ffi.Utf8> path,
    ffi.Pointer<ffi.Pointer<ditto_db_t>> out_db,
  ) {
    return _ditto_open(
      path,
      out_db,
    );
  }

  late final _ditto_openPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int32 Function(ffi.Pointer<pkg_ffi.Utf8>,
              ffi.Pointer<ffi.Pointer<ditto_db_t>>)>>('ditto_open');
  late final _ditto_open = _ditto_openPtr.asFunction<
      int Function(
          ffi.Pointer<pkg_ffi.Utf8>, ffi.Pointer<ffi.Pointer<ditto_db_t>>)>();

  /// Always safe to call; frees resources and invalidates pointer.
  void ditto_close(
    ffi.Pointer<ditto_db_t> db,
  ) {
    return _ditto_close(
      db,
    );
  }

  late final _ditto_closePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ditto_db_t>)>>(
          'ditto_close');
  late final _ditto_close =
      _ditto_closePtr.asFunction<void Function(ffi.Pointer<ditto_db_t>)>();

  /// Put a value. Returns 0 on success.
  int ditto_put(
    ffi.Pointer<ditto_db_t> db,
    ffi.Pointer<pkg_ffi.Utf8> key,
    ffi.Pointer<ffi.Uint8> data,
    int len,
  ) {
    return _ditto_put(
      db,
      key,
      data,
      len,
    );
  }

  late final _ditto_putPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int32 Function(ffi.Pointer<ditto_db_t>, ffi.Pointer<pkg_ffi.Utf8>,
              ffi.Pointer<ffi.Uint8>, ffi.Size)>>('ditto_put');
  late final _ditto_put = _ditto_putPtr.asFunction<
      int Function(ffi.Pointer<ditto_db_t>, ffi.Pointer<pkg_ffi.Utf8>,
          ffi.Pointer<ffi.Uint8>, int)>();

  /// Get a value into caller-provided buffer. If out_len is smaller than value,
  /// function sets *out_len to required size and returns 1 (buffer too small).
  /// Returns 0 on success, 2 if key not found, other non-zero on error.
  int ditto_get(
    ffi.Pointer<ditto_db_t> db,
    ffi.Pointer<pkg_ffi.Utf8> key,
    ffi.Pointer<ffi.Uint8> out_buf,
    ffi.Pointer<ffi.Size> inout_len,
  ) {
    return _ditto_get(
      db,
      key,
      out_buf,
      inout_len,
    );
  }

  late final _ditto_getPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int32 Function(ffi.Pointer<ditto_db_t>, ffi.Pointer<pkg_ffi.Utf8>,
              ffi.Pointer<ffi.Uint8>, ffi.Pointer<ffi.Size>)>>('ditto_get');
  late final _ditto_get = _ditto_getPtr.asFunction<
      int Function(ffi.Pointer<ditto_db_t>, ffi.Pointer<pkg_ffi.Utf8>,
          ffi.Pointer<ffi.Uint8>, ffi.Pointer<ffi.Size>)>();

  /// Delete a key. Returns 0 on success, 2 if key not found.
  int ditto_delete(
    ffi.Pointer<ditto_db_t> db,
    ffi.Pointer<pkg_ffi.Utf8> key,
  ) {
    return _ditto_delete(
      db,
      key,
    );
  }

  late final _ditto_deletePtr = _lookup<
      ffi.NativeFunction<
          ffi.Int32 Function(ffi.Pointer<ditto_db_t>,
              ffi.Pointer<pkg_ffi.Utf8>)>>('ditto_delete');
  late final _ditto_delete = _ditto_deletePtr.asFunction<
      int Function(ffi.Pointer<ditto_db_t>, ffi.Pointer<pkg_ffi.Utf8>)>();

  /// Subscribe to changes for all keys. Returns a subscription id (>=1) via out_sub_id.
  /// Returns 0 on success.
  int ditto_subscribe(
    ffi.Pointer<ditto_db_t> db,
    ditto_on_change_cb cb,
    ffi.Pointer<ffi.Void> user_data,
    ffi.Pointer<ffi.Int32> out_sub_id,
  ) {
    return _ditto_subscribe(
      db,
      cb,
      user_data,
      out_sub_id,
    );
  }

  late final _ditto_subscribePtr = _lookup<
      ffi.NativeFunction<
          ffi.Int32 Function(
              ffi.Pointer<ditto_db_t>,
              ditto_on_change_cb,
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<ffi.Int32>)>>('ditto_subscribe');
  late final _ditto_subscribe = _ditto_subscribePtr.asFunction<
      int Function(ffi.Pointer<ditto_db_t>, ditto_on_change_cb,
          ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Int32>)>();

  /// Unsubscribe by id. Returns 0 on success.
  int ditto_unsubscribe(
    ffi.Pointer<ditto_db_t> db,
    int sub_id,
  ) {
    return _ditto_unsubscribe(
      db,
      sub_id,
    );
  }

  late final _ditto_unsubscribePtr = _lookup<
      ffi.NativeFunction<
          ffi.Int32 Function(
              ffi.Pointer<ditto_db_t>, ffi.Int32)>>('ditto_unsubscribe');
  late final _ditto_unsubscribe = _ditto_unsubscribePtr
      .asFunction<int Function(ffi.Pointer<ditto_db_t>, int)>();

  /// Returns a null-terminated, static string (do not free).
  ffi.Pointer<pkg_ffi.Utf8> ditto_version() {
    return _ditto_version();
  }

  late final _ditto_versionPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<pkg_ffi.Utf8> Function()>>(
          'ditto_version');
  late final _ditto_version =
      _ditto_versionPtr.asFunction<ffi.Pointer<pkg_ffi.Utf8> Function()>();
}

final class ditto_db extends ffi.Opaque {}

typedef ditto_db_t = ditto_db;
typedef ditto_on_change_cbFunction = ffi.Void Function(
    ffi.Pointer<ffi.Void> user_data, ffi.Pointer<pkg_ffi.Utf8> key);
typedef Dartditto_on_change_cbFunction = void Function(
    ffi.Pointer<ffi.Void> user_data, ffi.Pointer<pkg_ffi.Utf8> key);

/// Callback signature for change notifications.
/// user_data is an opaque pointer provided at subscription time.
typedef ditto_on_change_cb
    = ffi.Pointer<ffi.NativeFunction<ditto_on_change_cbFunction>>;
